import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // applicationName:"PWA App",
  // appleMobileWebAppCapable:"yes",
  // appleMobileWebAppStatusBarStyle:"default",
  // appleMobileWebAppTitle:"PWA App",
  // description:"Best PWA App in the world",
  // mobileWebAppCapable:"yes",
  // msapplicationConfig:"/icons/browserconfig.xml",
  // msapplicationTileColor:"#2B5797",
  // msapplicationTapHighlight:"no",
  // themeColor:"#000000"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        {/* <meta name="application-name" content="PWA App" />
        <meta name="apple-mobile-web-app-title" content="PWA App" />
        <meta name="description" content="Best PWA App in the world" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="theme-color" content="#000000" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="shortcut icon" href="/favicon.ico" /> */}

      <body className={inter.className}>{children}</body>
    </html>
  )
}
